services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: university_api_db
      DATABASE_USER: university_api_user
      DATABASE_PASSWORD: university_api_password
    volumes:
      - .:/app
    ports:
      - 8000:8000
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: university_api_user
      POSTGRES_PASSWORD: university_api_password
      POSTGRES_DB: university_api_db
    

volumes:
  postgres_data:
